In [37]:
import pandas as pd
from sqlalchemy import create_engine

In [38]:
url = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet"
df_taxi = pd.read_parquet(url)

df_taxi.to_parquet("green_tripdata_2025-11.parquet", index=False)
schema = {
    "VendorID": "Int64",
    "lpep_pickup_datetime": "datetime64[us]",
    "lpep_dropoff_datetime": "datetime64[us]",
    "store_and_fwd_flag": "string",
    "RatecodeID": "Int64",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "ehail_fee": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "payment_type": "Int64",
    "trip_type": "Int64",
    "congestion_surcharge": "float64",
    "cbd_congestion_fee": "float64",
}
df_taxi = df.astype(schema)

df_taxi.dtypes

VendorID                          Int64
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               string
RatecodeID                        Int64
PULocationID                      Int64
DOLocationID                      Int64
passenger_count                   Int64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                      Int64
trip_type                         Int64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [39]:

url = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"

df_zones = pd.read_csv(url)

df_zones.to_parquet("taxi_zone_lookup.parquet", index=False)

df_zones.dtypes

LocationID      int64
Borough           str
Zone              str
service_zone      str
dtype: object

In [40]:
engine = create_engine("postgresql+psycopg://root:root@localhost:5432/ny_taxi")

print(pd.io.sql.get_schema(df_taxi, name="green_taxi_data_nov_25", con=engine))
print(pd.io.sql.get_schema(df_zones, name="taxi_zone_lookup", con=engine))

CREATE TABLE green_taxi_data_nov_25 (
	"VendorID" BIGINT,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" BIGINT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type BIGINT,
	trip_type BIGINT,
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)



CREATE TABLE taxi_zone_lookup (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [41]:
df_taxi.head(n=0).to_sql(name='green_taxi_data_nov_25', con=engine, if_exists='replace')
df_zones.head(n=0).to_sql(name='taxi_zone_lookup', con=engine, if_exists='replace')

0

In [42]:

df_taxi.to_sql(
        name="green_taxi_data_nov_25",
        con=engine,
        if_exists="append",
        index=False
    )

df_zones.to_sql(
        name="taxi_zones",
        con=engine,
        if_exists="append",
        index=False
    )

-1

In [43]:
df_taxi.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1,74,42,1,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1,1,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1,74,42,2,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2,1,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1,83,160,1,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1,1,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1,166,127,1,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1,1,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1,166,262,1,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1,1,2.75,0.0

In [44]:
df_zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

SQL HW:
Q3:
select count(*) from green_taxi_data_nov_25 where EXTRACT ('MONTH' from lpep_pickup_datetime) = 11 and trip_distance <= 1
Q4:
select date(lpep_pickup_datetime) from  green_taxi_data_nov_25 where trip_distance < 100 order by trip_distance DESC limit 1
Q5:
SELECT
    tz."Zone"
FROM taxi_zones AS tz
JOIN green_taxi_data_nov_25 AS gt
    ON gt."PULocationID" = tz."LocationID"
GROUP BY tz."Zone"
ORDER BY SUM(gt.total_amount) DESC
Limit 1;
Q6: 

SELECT
  dtz."Zone"
FROM taxi_zones AS tz
JOIN green_taxi_data_nov_25 AS gt
    ON gt."PULocationID" = tz."LocationID"
JOIN taxi_zones as dtz on gt."DOLocationID" = dtz."LocationID"
    where tz."Zone" = 'East Harlem North'
    and EXTRACT ('MONTH' from lpep_pickup_datetime) = 11

    order by tip_amount DESC LIMIT 1